version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_CHARSET: utf8mb4
    volumes:
      - ./.mysql-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    depends_on:
      - big-event
    networks:
      - backend
  big-event:
    build:
      context: .
      dockerfile: Dockerfile
    image: big-event
    container_name: big-event
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      - frontend
      - backend
networks:
  frontend:
  backend: